### ISSUE TITLE
webapp.py FAILED

### ISSUE THREAD

**Issue by asifehmad** [andrewssobral/llama-webapp#1]
Hi,
thanks for the work. Was just trying to run the app came across this issue:

`
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "webapp.py", line 75, in <module>
    generator = load(
  File "webapp.py", line 47, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=0 but world size is 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1784) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
webapp.py FAILED
------------------------------------------------------------
```
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-06_17:50:47
  host      : 9da8e4abbd0f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1784)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Could you please check this?

Thanks,

**Comment by andrewssobral** [comment]
Hello @asifehmad , thank you for your message.
I think this issue is related to this https://github.com/facebookresearch/llama/issues/72 and this https://github.com/facebookresearch/llama/issues/63
Do you have all files downloaded from LLaMA ?
Which GPU are you using?

**Comment by asifehmad** [comment]
> Hello @asifehmad , thank you for your message. I think this issue is related to this [facebookresearch/llama#72](https://github.com/facebookresearch/llama/issues/72) and this [facebookresearch/llama#63](https://github.com/facebookresearch/llama/issues/63) Do you have all files downloaded from LLaMA ? Which GPU are you using?

Hi @andrewssobral , thanks for the response. I didn't have the files. For the files, I now cloned this HF [repository](https://huggingface.co/nyanko7/LLaMA-7B) and set the path in `webapp.py ` it worked!!!
I ran it Google Colab with A100 40GiB.

**Comment by andrewssobral** [comment]
Perfect! congrats @asifehmad ! ;-)
